import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

export async function GET(request: NextRequest) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const searchParams = request.nextUrl.searchParams;
  const reconId = searchParams.get("recon_id");

  if (!reconId) {
    return NextResponse.json({ error: "Missing recon_id" }, { status: 400 });
  }

  // Fetch reconciliation with matches
  const { data: recon, error: reconError } = await supabase
    .from("reconciliations")
    .select("*")
    .eq("id", reconId)
    .single();

  if (reconError || !recon) {
    return NextResponse.json({ error: "Reconciliation not found" }, { status: 404 });
  }

  const { data: matches } = await supabase
    .from("recon_matches")
    .select("*")
    .eq("recon_id", reconId);

  // Get related transactions
  const myTxIds = (matches || []).map((m) => m.my_tx_id).filter(Boolean);
  const theirTxIds = (matches || []).map((m) => m.their_tx_id).filter(Boolean);
  const allTxIds = [...new Set([...myTxIds, ...theirTxIds])];

  let transactions: Record<string, unknown>[] = [];
  if (allTxIds.length > 0) {
    const { data } = await supabase
      .from("transactions")
      .select("*")
      .in("id", allTxIds);
    transactions = data || [];
  }

  const txMap = new Map(transactions.map((t) => [(t as { id: string }).id, t]));

  // Build simple text-based PDF content (HTML for now)
  const summary = {
    matched: (matches || []).filter((m) => m.match_status === "matched").length,
    diff: (matches || []).filter((m) => m.match_status === "diff").length,
    missing: (matches || []).filter((m) => m.match_status === "missing").length,
  };

  const html = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>DuiZhang Reconciliation Report</title>
<style>
body { font-family: sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
h1 { font-size: 24px; border-bottom: 2px solid #333; padding-bottom: 8px; }
.summary { display: flex; gap: 20px; margin: 20px 0; }
.stat { padding: 12px 20px; border-radius: 8px; text-align: center; }
.matched { background: #dcfce7; color: #166534; }
.diff { background: #fef9c3; color: #854d0e; }
.missing { background: #fee2e2; color: #991b1b; }
.stat-num { font-size: 28px; font-weight: bold; }
.stat-label { font-size: 12px; }
table { width: 100%; border-collapse: collapse; margin-top: 20px; }
th, td { border: 1px solid #ddd; padding: 8px; text-align: left; font-size: 13px; }
th { background: #f5f5f5; }
.tag { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; }
.tag-matched { background: #dcfce7; color: #166534; }
.tag-diff { background: #fef9c3; color: #854d0e; }
.tag-missing { background: #fee2e2; color: #991b1b; }
</style>
</head>
<body>
<h1>DuiZhang - Reconciliation Report</h1>
<p>Period: ${recon.date_from} to ${recon.date_to}</p>
<div class="summary">
  <div class="stat matched"><div class="stat-num">${summary.matched}</div><div class="stat-label">Matched</div></div>
  <div class="stat diff"><div class="stat-num">${summary.diff}</div><div class="stat-label">Differences</div></div>
  <div class="stat missing"><div class="stat-num">${summary.missing}</div><div class="stat-label">Missing</div></div>
</div>
<table>
<tr><th>Status</th><th>My Transaction</th><th>Their Transaction</th><th>Detail</th></tr>
${(matches || [])
  .map((m) => {
    const myTx = m.my_tx_id ? (txMap.get(m.my_tx_id) as Record<string, unknown> | undefined) : null;
    const theirTx = m.their_tx_id ? (txMap.get(m.their_tx_id) as Record<string, unknown> | undefined) : null;
    return `<tr>
      <td><span class="tag tag-${m.match_status}">${m.match_status}</span></td>
      <td>${myTx ? `${myTx.item_name} - ¥${myTx.amount} (${myTx.date})` : "-"}</td>
      <td>${theirTx ? `${theirTx.item_name} - ¥${theirTx.amount} (${theirTx.date})` : "-"}</td>
      <td>${m.diff_detail || "-"}</td>
    </tr>`;
  })
  .join("")}
</table>
<p style="margin-top: 40px; font-size: 11px; color: #999;">Generated by DuiZhang</p>
</body>
</html>`;

  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `inline; filename="reconciliation-${reconId}.html"`,
    },
  });
}
